### ISSUE TITLE
list of things we want o add or change to schema.org

### ISSUE THREAD

**Issue by ghost** [geo4web-testbed/geo-extension-to-schemaorg#1]
Things that are part of a Dataset
The type of a Place, GeoShape etc
The source of a record.

Quick solution: if we make everything that we model also of type schema:Dataset then we can use the CreativeWork properties.

**Comment by cportele** [comment]
My current thought was to use schema:Place for features and schema:Dataset for each WFS/dataset as well as for each subset that is defined by a query (e.g. the collection of features for each woonplaats).

Then we can map several of the items in the WFS capabilities to the Dataset properties, e.g. ows:Title, ows:Abstract, ows:Keyword, inspire_common:DefaultLanguage, ows:ServiceProvider, ows:Fees, ows:AccessConstraints and maybe more.

**Comment by ghost** [comment]
Sounds good to me! I was trying to solve the "type" and "source" property in the AAN dataset. If these are properties that are on the Dataset level (I assume this is so..but how can we be sure?) then your suggestion solves this

**Comment by cportele** [comment]
Ah ok. I think these properties will have to be extensions and not be mapped to any of the schema.org properties as you have mapped them right now, i.e.

```
...
"aan:versiebron" : "luchtfoto 2014",
"aan:type" : "BTR-landbouw",
...
```

In this case, if these properties represent useful groupings, we might also use any of the two properties to group features/Places so we might represent them in this case also as

```
...
"aan:versiebron" : "http://example.com/aan/type/luchtfoto2014",
"aan:type" : "http://example.com/aan/type/BTR-landbouw",
...
```

where both of these are Datasets and reference all features/Places that have the same versiebron or type value.

**Comment by ghost** [comment]
I did map those properties as extensions in the JSON-LD, see the prefix sgeo which refers to the context http://geo.schema.org (I also used the bib example..;-) ). The sgeo voc is specified [here](https://github.com/geo4web-testbed/geo-extension-to-schemaorg). This is just a placeholder for now..the semantics is really not clever..must fix this later. 
I like your suggestion of grouping, to make them a type. It seems that the data publisher will need a lot of help with the mapping..we need an intuitive UI for this (better than the Google validator..)

**Comment by cportele** [comment]
Some additional thoughts about Dataset:

The data in a WFS is clearly a Dataset (as stated at the bottom of https://schema.org/Dataset, the dataset definition is taken from DCAT). If the features would be CreativeWorks, then we could use the isPartOf/hasPart properties to specify the relationship between a feature and its dataset.

However, if we map each feature to a Place then we cannot use isPartOf/hasPart.

I think what we (again) struggle with is the fact that in spatial datasets a feature represents two aspects: one is the real-world entity and its properties (that can be observed in the real-world) and the other is fact that this is a documentation of that real-world entity along with properties that describe the document, not the real-world entity. In schema.org the latter would be a CreativeWork. So, an inspireadressen or aan feature could be seen as both a Place and a CreativeWork.

We could represent a feature as a graph with both a Place and CreativeWork object. While this sounds "clean" and seprates the subjects, I am concerned that this is just too complex.

My current thinking is that we should just make the features a Place, the dataset and subsets of it a Dataset (or a new subtype of Dataset, if needed), and create new properties in an extension that link Places (or Things?) and Datasets, e.g. describedIn/describes.

It seems to me as if the same issue would occur with other non-spatial datasets, e.g. a car register.

**Comment by pvgenuchten** [comment]
I have a similar challenge with the schema mapping from iso19139 to schema.org, is the thing that I'm mapping the actual dataset or am I mapping a document that describes the dataset, for example Thing.url would it link to the actual data or to the page describing the dataset and the distribution links to the actual dataset

**Comment by dvh** [comment]
As we will encounter the same challenges I'd like to give my thoughts on this... Because it's a test, why don't we publish the same data in multiple ways (with different context approaches) and see what happens?

**Comment by cportele** [comment]
@dvh - sounds good to me. Being able to test different approaches is a nice thing about this testbed. 

I will hopefully have a more complete example of the resources ready later this week, so next week's meeting is a good opportunity to discuss some of this.

**Comment by ghost** [comment]
@dvh @cportele @pvgenuchten this is a common issue in Linked Data land.
There are several solutions for this. The most important question that you have to ask youself is: are we dealing with the same Thing (meaning, does it (= the data resource) _need_ the same resource identifier) or is it acceptable that we make separate resource identifiers.
If it needs the same identifier, then you can still say that the resource belongs to more than one type. In Semantic web, a rdf:type is a set, a collection. So a resource can belong to more than one set. (But it is clear that a feature is different from a geometry object)
See for example DBpedia-NL: the resource Amsterdam is a Place, Location and a gml:_Feature
In DBpedia they also have implemented a solution for @pvgenuchten 's issue: "is the thing that I'm mapping the actual dataset or am I mapping a document that describes the dataset" . The solution for this is: content negotiation and URI rewriting. If you request for the resource and are a browser, then you get a HTML page. This page has a different URL. Try it: http://nl.dbpedia.org/resource/Amsterdam. If you are a RDF client ("Accept: application/rdf+xml"), you get yet another URL. Nowadays some people think this is overdone and one URL should be fine for a resource, independent of MIME type requested. But we could use this principle if it serves our needs. This conneg principle for geo is also suggested by the guys from NeoGeo a couple of years ago. See: http://geovocab.org/doc/neogeo.html (it is in the Introduction)
It would also be good to have a look at what the people from GeoKnow did, just to adopt the same  principles.

If a different identifier is needed then what people mostly do is put it (= the data resource) in another context. The context represents the point of view. So we could for example make these contexts:
_http://example.com/place/_ and _http://example.com/dataset/_ then you get:

```
http://example.com/place/1234 a schema:Place
http://example.com/dataset/1234 a schema:Dataset
```

That I am using the same qname (the last part in the URL) is not necessary, but it could be useful for querying. I can also omit the /place or /dataset , but then I must take different qnames.
There is a property that connects schema:Place with schema:Dataset
http://example.com/dataset/1234  schema:spatial http://example.com/place/1234

@cportele: what makes you think this is too complex? what problems do you forsee?
@dvh: I think what will happen if we try out different mappings is that our resources will probably be in different indexes. The person that does the mapping must realise this, and must while mapping put the emphasis on how (s)he wants the data to be found.

**Comment by cportele** [comment]
@lieke: Having two resources (a Place and a CreativeWork) is more complex than having just a single resource (a Place) to process. 

Those with a geo background will ask why it is necessary as having a single feature was always good enough for their purposes. But I think it is also easier for most web developers as dealing with one resource is easier than dealing with two. There may be also other condierations, e.g. you will probably end up with more requests in an application.

Having separate Place and CreativeWork resources is semantically more clean and may be important for reasoning etc., but how important is that for most?

**Comment by dvh** [comment]
@liekeverhelst I suggest we are going to find it out and use different approaches for topic 3 and topic 4. Also for the content negotiation (yes, we're Accept Header fetisjists ;-))

**Comment by dvh** [comment]
@cportele I believe that SEO best practices (which are quite relevant for web developers) recommend that having multiple types isn't a problem. wwww.apiwise.nl for example is both a 'Website' and an 'Organization'.

**Comment by cportele** [comment]
@dvh OK, but in your case you have one resource with multiple types, this is different from having two resources with two URLs. Or am I missing something?

**Comment by dvh** [comment]
@cportele sorry, I think I missed something :)

**Comment by ghost** [comment]
@cportele : "but how important is that [semantics] for most?" Personally I am a strong advocate for making the semantics right. Because if you don't, you are missing the smart in smart data (not only reasoning but also validation and querying! ..so basically data quality & ease of processing). I know that a lot of people ignore this, but I wonder if they know what they are missing. 
Anyway..this is an interesting discussion that we perhaps should have in person next Friday (topic 4) and Tuesday (plenary) and summarise here in this issue for the general audience.

**Comment by ghost** [comment]
continue in a new issue. This makes the discussion more focussed.
